apiVersion: v1
kind: Service
metadata:
  name: tcp-server
  labels:
    service: tcp-server
    appType: tradeshift-component
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tcp-server.eu-west-1.test.ts.sv
    kubernetes.io/ingress.class: nginx
    team: dev-prod
spec:
  type: LoadBalancer
  ports:
    - port: 3333
      targetPort: 3333
      protocol: TCP
      name: tcp-server
  selector:
    app: tcp-server
